label: Galerie fotek
fields:
  - name: caption
    type: text
    label: Titulek galerie

  - name: columns
    type: select
    label: Počet sloupců
    options: [2, 3, 4]
    default: 3

  - name: images
    type: list
    label: Obrázky
    item_fields:
      - name: src
        type: image
        label: Soubor
        required: true
      - name: alt
        type: text
        label: Popisek
